name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
    uses: docker/login-action@v1
    with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ github.token }}
      - name: Build the hello-docker Docker image
    run: |
          docker build . --tag ghcr.io/sapphyree/poole-internal:latest
          docker run ghcr.io/sapphyree/poole-internal:latest
          docker push ghcr.io/sapphyree/poole-internal:latest
